# Hardcoded Tcl script for assigning pins to lamps_lamps_lamps_lamps variable

# Assign pins to lamps_lamps_lamps_lamps variable using FPGA Pin Numbers from the table
set_location_assignment PIN_AE26 -to lamps_lamps\[0\] 
set_location_assignment PIN_AE27 -to lamps_lamps\[1\] 
set_location_assignment PIN_AE28 -to lamps_lamps\[2\] 
set_location_assignment PIN_AG27 -to lamps_lamps\[3\] 
set_location_assignment PIN_AF28 -to lamps_lamps\[4\] 
set_location_assignment PIN_AG28 -to lamps_lamps\[5\] 
set_location_assignment PIN_AH28 -to lamps_lamps\[6\] 
set_location_assignment PIN_AJ29 -to lamps_lamps\[7\] 
set_location_assignment PIN_AH29 -to lamps_lamps\[8\] 
set_location_assignment PIN_AH30 -to lamps_lamps\[9\] 
set_location_assignment PIN_AG30 -to lamps_lamps\[10\] 
set_location_assignment PIN_AF29 -to lamps_lamps\[11\] 
set_location_assignment PIN_AF30 -to lamps_lamps\[12\] 
set_location_assignment PIN_AD27 -to lamps_lamps\[13\] 
set_location_assignment PIN_AB23 -to lamps_lamps\[14\] 
set_location_assignment PIN_AE29 -to lamps_lamps\[15\] 
set_location_assignment PIN_AD29 -to lamps_lamps\[16\] 
set_location_assignment PIN_AC28 -to lamps_lamps\[17\] 
set_location_assignment PIN_AD30 -to lamps_lamps\[18\] 
set_location_assignment PIN_AC29 -to lamps_lamps\[19\] 
set_location_assignment PIN_AC30 -to lamps_lamps\[20\] 
set_location_assignment PIN_AD26 -to lamps_lamps\[21\] 
set_location_assignment PIN_AC27 -to lamps_lamps\[22\] 
set_location_assignment PIN_AD25 -to lamps_lamps\[23\] 
set_location_assignment PIN_AC25 -to lamps_lamps\[24\] 
set_location_assignment PIN_AB28 -to lamps_lamps\[25\] 
set_location_assignment PIN_AB25 -to lamps_lamps\[26\] 
set_location_assignment PIN_AB22 -to lamps_lamps\[27\] 
set_location_assignment PIN_AA24 -to lamps_lamps\[28\] 
set_location_assignment PIN_Y23 -to lamps_lamps\[29\] 
set_location_assignment PIN_Y24 -to lamps_lamps\[30\] 
set_location_assignment PIN_W22 -to lamps_lamps\[31\] 
set_location_assignment PIN_W24 -to lamps_lamps\[32\] 
set_location_assignment PIN_V23 -to lamps_lamps\[33\] 
set_location_assignment PIN_W25 -to lamps_lamps\[34\] 
set_location_assignment PIN_V25 -to lamps_lamps\[35\] 
set_location_assignment PIN_AA28 -to lamps_lamps\[36\] 
set_location_assignment PIN_Y27 -to lamps_lamps\[37\] 
set_location_assignment PIN_AB27 -to lamps_lamps\[38\] 
set_location_assignment PIN_AB26 -to lamps_lamps\[39\] 
set_location_assignment PIN_AA26 -to lamps_lamps\[40\] 
set_location_assignment PIN_AA25 -to lamps_lamps\[41\] 

# Print confirmation
puts "Pin assignments for lamps_lamps_lamps_lamps variable completed."
